apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nimbus.fullname" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "nimbus.name" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  NEXTAUTH_SECRET: {{ .Values.auth.secret | quote }}
  NEXTAUTH_URL: {{ .Values.auth.url | quote }}
  ENCRYPTION_KEY: {{ .Values.encryption.key | quote }}
  NODE_ENV: "production"
