apiVersion: v1
kind: Service
metadata:
  name: {{ include "nimbus.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "nimbus.name" . }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nimbus.name" . }}
    app.kubernetes.io/component: web
